# Generated by Django 5.1.3 on 2024-11-18 02:29

import mtambo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtambo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('DEVELOPER', 'developer'), ('MAINTENANCE', 'maintenance'), ('TECHNICIAN', 'technician')], default=mtambo.models.AccountType['DEVELOPER'], max_length=50),
        ),
    ]
